version: "3.9"
services:
  bot:
    build: .
    command: python run.py
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL:-sqlite+aiosqlite:///data/db.sqlite3}
    volumes:
      - ./session:/app/session
      - ./data:/app/data
      - ./keywords.txt:/app/keywords.txt:ro
    restart: unless-stopped
