version: "3.9"
services:
  bot:
    build: .
    command: python run.py
    env_file:
      - .env
    volumes:
      - ./session:/app/session
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
